# -*- coding: utf-8 -*-
"""Smart Recruitment Assistant Using Machine Learning

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QVLo85borxXnCc8XfLVgJmTZ0mlP7jwr

# Feature Engineering
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv("aug_train.csv")

df.head()

df.shape

df.info()

df.isnull().sum()

df.drop("enrollee_id", axis=1, inplace=True)

df.columns

df.drop("enrollee_id", axis=1, inplace=True)

df.columns.tolist()

for col in df.columns:
    if df[col].dtype == "object":
        df[col] = df[col].fillna(df[col].mode()[0])
    else:
        df[col] = df[col].fillna(df[col].median())

df.isnull().sum()

from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

for col in df.select_dtypes(include='object').columns:
    df[col] = le.fit_transform(df[col])

df.info()

from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

for col in df.select_dtypes(include=['object']).columns:
    df[col] = le.fit_transform(df[col])

df.info()

df.dtypes

df.head()

from sklearn.model_selection import train_test_split

X = df.drop("target", axis=1)
y = df["target"]

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

X_train.shape, X_test.shape

from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

lr = LogisticRegression(max_iter=1000)

lr.fit(X_train, y_train)

y_pred = lr.predict(X_test)

accuracy_score(y_test, y_pred)

y_pred = lr.predict(X_test)

accuracy_score(y_test, y_pred)

print(classification_report(y_test, y_pred))

cm = confusion_matrix(y_test, y_pred)
print(cm)

import seaborn as sns
import matplotlib.pyplot as plt

plt.figure(figsize=(5,4))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues')
plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.title("Confusion Matrix")
plt.show()

from sklearn.ensemble import RandomForestClassifier

rf = RandomForestClassifier(random_state=42)

rf.fit(X_train, y_train)

y_pred_rf = rf.predict(X_test)

accuracy_score(y_test, y_pred_rf)

models = ["Logistic Regression", "Random Forest"]

scores = [0.7654, 0.7659]

plt.figure(figsize=(6,4))
plt.bar(models, scores)
plt.ylabel("Accuracy")
plt.title("Model Comparison")
plt.show()

importance = pd.DataFrame({
    "Feature": X.columns,
    "Importance": rf.feature_importances_
})

importance = importance.sort_values(
    by="Importance",
    ascending=False
)

importance.head(10)

plt.figure(figsize=(8,5))
plt.barh(importance["Feature"], importance["Importance"])
plt.title("Feature Importance")
plt.gca().invert_yaxis()
plt.show()

import seaborn as sns
import matplotlib.pyplot as plt

plt.figure(figsize=(6,4))
sns.countplot(x='target', data=df)
plt.title("Target Distribution")
plt.show()

plt.figure(figsize=(8,5))
sns.countplot(x='education_level', data=df)
plt.title("Education Level Distribution")
plt.xticks(rotation=45)
plt.show()

plt.figure(figsize=(10,5))
sns.countplot(x='experience', data=df)
plt.title("Experience Distribution")
plt.xticks(rotation=45)
plt.show()

plt.figure(figsize=(8,5))
sns.histplot(df['training_hours'], bins=30, kde=True)
plt.title("Training Hours Distribution")
plt.show()

plt.figure(figsize=(12,8))
sns.heatmap(df.corr(), annot=True, cmap="coolwarm", fmt=".2f")
plt.title("Correlation Matrix")
plt.show()

importance = pd.DataFrame({
    'Feature': X.columns,
    'Importance': rf.feature_importances_
})

importance = importance.sort_values(by='Importance', ascending=False)

importance

plt.figure(figsize=(8,5))
sns.barplot(x='Importance', y='Feature', data=importance)
plt.title("Feature Importance")
plt.show()

import joblib

joblib.dump(rf, "recruitment_model.pkl")

import os
os.listdir()

df['experience'].unique()

df['training_level'] = pd.cut(
    df['training_hours'],
    bins=[0, 20, 50, df['training_hours'].max()],
    labels=['Low', 'Medium', 'High'],
    include_lowest=True
)

df[['training_hours', 'training_level']].head()

from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
df['training_level'] = le.fit_transform(df['training_level'])

X = df.drop("target", axis=1)
y = df["target"]

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42
)

from sklearn.linear_model import LogisticRegression

lr = LogisticRegression(max_iter=1000)

lr.fit(X_train, y_train)

y_pred = lr.predict(X_test)

from sklearn.ensemble import RandomForestClassifier

rf = RandomForestClassifier(random_state=42)

rf.fit(X_train, y_train)

y_pred_rf = rf.predict(X_test)

from sklearn.metrics import classification_report

print("Logistic Regression")
print(classification_report(y_test, y_pred))

print("\nRandom Forest")
print(classification_report(y_test, y_pred_rf))

comparison = pd.DataFrame({
    'Model': ['Logistic Regression', 'Random Forest'],
    'Accuracy': [0.76, 0.77],
    'Precision': [0.56, 0.54],
    'Recall': [0.24, 0.40],
    'F1-Score': [0.34, 0.46]
})

comparison

comparison.set_index('Model').plot(kind='bar', figsize=(8,5))
plt.title("Model Performance Comparison")
plt.ylabel("Score")
plt.xticks(rotation=0)
plt.show()

# حساب احتمالية قبول كل مرشح
probabilities = rf.predict_proba(X)[:, 1]

# إضافة الاحتمالية للداتا
df["Hiring_Probability"] = probabilities

# ترتيب المرشحين
top10 = df.sort_values(
    by="Hiring_Probability",
    ascending=False
).head(10)

# عرض أفضل 10 مرشحين
top10

"""# Business Insights

- Random Forest achieved the best overall performance with an accuracy of approximately 77%.

- Feature Engineering improved the dataset by creating the new feature "training_level".

- The Candidate Ranking System identifies the Top 10 candidates with the highest hiring probability, helping HR teams prioritize applicants.

- Machine Learning can reduce manual screening effort and support recruitment decisions.

- Future improvements include Hyperparameter Tuning and Cross Validation to further improve model performance.
"""

from sklearn.model_selection import GridSearchCV
from sklearn.ensemble import RandomForestClassifier

# الإعدادات اللي هيجربها
param_grid = {
    'n_estimators': [100, 200],
    'max_depth': [10, 20, None],
    'min_samples_split': [2, 5]
}

# إنشاء النموذج
rf = RandomForestClassifier(random_state=42)

# Grid Search
grid_search = GridSearchCV(
    estimator=rf,
    param_grid=param_grid,
    cv=3,
    scoring='accuracy',
    n_jobs=-1
)

# التدريب
grid_search.fit(X_train, y_train)

# أفضل إعدادات
print("Best Parameters:", grid_search.best_params_)
print("Best Score:", grid_search.best_score_)

# استخدام أفضل نموذج
best_rf = grid_search.best_estimator_

# التنبؤ
y_pred_best = best_rf.predict(X_test)

# تقييم النموذج
from sklearn.metrics import accuracy_score, classification_report

print("Accuracy:", accuracy_score(y_test, y_pred_best))
print("\n")
print(classification_report(y_test, y_pred_best))

# إنشاء عمود جديد يحدد حالة المرشح

def candidate_status(x):
    if x == 0:
        return "Graduate"
    else:
        return "Student"

df["candidate_status"] = df["enrolled_university"].apply(candidate_status)

df[["enrolled_university", "candidate_status"]].head()

def experience_level(exp):
    if exp <= 1:
        return "Fresher"
    elif exp <= 5:
        return "Junior"
    elif exp <= 10:
        return "Mid-Level"
    else:
        return "Senior"

df["experience_level"] = df["experience"].apply(experience_level)

df[["experience", "experience_level"]].head(10)

from sklearn.preprocessing import LabelEncoder

le_status = LabelEncoder()
df["candidate_status"] = le_status.fit_transform(df["candidate_status"])

le_exp = LabelEncoder()
df["experience_level"] = le_exp.fit_transform(df["experience_level"])

X = df.drop("target", axis=1)
y = df["target"]

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42
)

best_rf.fit(X_train, y_train)

y_pred = best_rf.predict(X_test)

from sklearn.metrics import accuracy_score, classification_report

print("Accuracy:", accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred))

"""# Candidate Ranking System

The trained Random Forest model predicts the hiring probability for each candidate.
Candidates are ranked based on their predicted hiring probability to help HR teams identify the best applicants quickly.

The table below shows the Top 10 candidates with the highest hiring probability.
"""

top10 = top10.copy()

top10["candidate_status"] = top10["candidate_status"].map({
    0: "Graduate",
    1: "Student"
})

top10["experience_level"] = top10["experience_level"].map({
    0: "Fresher",
    1: "Junior",
    2: "Mid-Level",
    3: "Senior"
})

top10["training_level"] = top10["training_level"].map({
    0: "Low",
    1: "Medium",
    2: "High"
})

top10

from sklearn.model_selection import cross_val_score

scores = cross_val_score(best_rf, X, y, cv=5)

print("Cross Validation Scores:")
print(scores)

print("\nAverage Accuracy:")
print(scores.mean())

from sklearn.metrics import roc_curve, auc
import matplotlib.pyplot as plt

# احتمالات التنبؤ
y_prob = best_rf.predict_proba(X_test)[:, 1]

# حساب ROC
fpr, tpr, thresholds = roc_curve(y_test, y_prob)
roc_auc = auc(fpr, tpr)

# الرسم
plt.figure(figsize=(6,6))
plt.plot(fpr, tpr, label=f"AUC = {roc_auc:.2f}")
plt.plot([0,1], [0,1], linestyle='--')
plt.xlabel("False Positive Rate")
plt.ylabel("True Positive Rate")
plt.title("ROC Curve")
plt.legend()
plt.show()

print("AUC Score:", roc_auc)

import joblib

joblib.dump(best_rf, "recruitment_model_final.pkl")

print("Model Saved Successfully!")

import os
os.listdir()

!pip install xgboost

from xgboost import XGBClassifier

xgb = XGBClassifier(
    random_state=42,
    eval_metric='logloss'
)

xgb.fit(X_train, y_train)

y_pred_xgb = xgb.predict(X_test)

from sklearn.metrics import accuracy_score

accuracy = accuracy_score(y_test, y_pred_xgb)
print("XGBoost Accuracy:", accuracy)

from sklearn.metrics import confusion_matrix

cm = confusion_matrix(y_test, y_pred_xgb)
print(cm)

from sklearn.metrics import classification_report

print(classification_report(y_test, y_pred_xgb))

import matplotlib.pyplot as plt

models = ['Logistic Regression', 'Random Forest', 'XGBoost']
accuracies = [0.7654, 0.7659, 0.7696]

plt.figure(figsize=(7,5))
plt.bar(models, accuracies)
plt.ylabel("Accuracy")
plt.title("Model Comparison")
plt.ylim(0.70,0.80)

for i,v in enumerate(accuracies):
    plt.text(i, v+0.001, f"{v:.3f}", ha='center')

plt.show()

import joblib

joblib.dump(xgb, "recruitment_model_final.pkl")

